webtalk_init -webtalk_dir /home/twinborn/Data/FPGA/PYNQ/AXIStream/AXIStreamTest.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-04-08 14:37:48" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211734358_1777544771_210705298_702" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "mm4i23b6istiuc7qla9t9d2nq4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E31225 @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2977.194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.744 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1586327588000" -context "sdk\\\\bsp/1586327588000"
webtalk_add_data -client sdk -key hwid -value "1586324868000" -context "sdk\\\\bsp/1586327588000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1586327588000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1586327588000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1586327588000"
webtalk_add_data -client sdk -key uid -value "1586327589000" -context "sdk\\\\application/1586327589000"
webtalk_add_data -client sdk -key hwid -value "1586324868000" -context "sdk\\\\application/1586327589000"
webtalk_add_data -client sdk -key bspid -value "1586327588000" -context "sdk\\\\application/1586327589000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1586327589000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1586327589000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1586327589000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1586327589000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1586327589000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1586327589000"
webtalk_add_data -client sdk -key projSize -value "306.46875" -context "sdk\\\\application/1586327589000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1586327868529"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1586327868529"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1586327868529"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1586327868529"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1586327868529"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1586327868529"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1586327868529"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1586327868529"
webtalk_transmit -clientid 3260166737 -regid "211734358_1777544771_210705298_702" -xml /home/twinborn/Data/FPGA/PYNQ/AXIStream/AXIStreamTest.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/twinborn/Data/FPGA/PYNQ/AXIStream/AXIStreamTest.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/twinborn/Data/FPGA/PYNQ/AXIStream/AXIStreamTest.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
